#!/usr/bin/env python3
"""Export Facebook cookies for yt-dlp (bypasses Edge/Chrome DPAPI on Windows).

Why: Chromium cookie DBs are often unreadable by yt-dlp on Windows (DPAPI /
app-bound encryption). Playwright opens a real browser window; after you log
into Facebook once, cookies are written as Netscape cookies.txt that yt-dlp
can load via YTDLP_COOKIES_FILE.

Usage (from repo root, with api/.venv):

  api/.venv/Scripts/python.exe -m pip install playwright
  api/.venv/Scripts/python.exe -m playwright install chromium
  api/.venv/Scripts/python.exe scripts/export_facebook_cookies.py

Then set in api/.env:

  YTDLP_COOKIES_FILE=D:/Coding/Dubby/api/fb-cookies.txt

Restart API/worker and retry the facebook.com/share/r/… link.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "api" / "fb-cookies.txt"


def _require_playwright():
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:  # pragma: no cover - setup helper
        print(
            "playwright 가 없습니다. 먼저 설치하세요:\n"
            "  api/.venv/Scripts/python.exe -m pip install playwright\n"
            "  api/.venv/Scripts/python.exe -m playwright install chromium",
            file=sys.stderr,
        )
        raise SystemExit(1) from exc
    return sync_playwright


def _write_netscape(cookies: list[dict], dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by scripts/export_facebook_cookies.py",
        "# This file is for local yt-dlp / Dubby use only.",
        "",
    ]
    now = int(time.time())
    for item in cookies:
        domain = (item.get("domain") or "").strip()
        if not domain:
            continue
        # Netscape: TRUE means cookie applies to subdomains of domain.
        subdomain_flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = item.get("path") or "/"
        secure = "TRUE" if item.get("secure") else "FALSE"
        expires = item.get("expires")
        if expires is None or int(expires) < 0:
            expires_i = now + 86400 * 30
        else:
            expires_i = int(expires)
        name = item.get("name") or ""
        value = item.get("value") or ""
        if not name:
            continue
        lines.append(
            "\t".join(
                [
                    domain,
                    subdomain_flag,
                    path,
                    secure,
                    str(expires_i),
                    name,
                    value,
                ]
            )
        )
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help=f"Netscape cookies.txt path (default: {DEFAULT_OUT})",
    )
    parser.add_argument(
        "--timeout-sec",
        type=int,
        default=300,
        help="Seconds to wait for Facebook login when stdin is not a TTY",
    )
    args = parser.parse_args()
    sync_playwright = _require_playwright()

    print("브라우저가 열리면 Facebook에 로그인하세요.")
    print("로그인 후 뉴스피드/홈이 보이면 이 창으로 돌아와 Enter를 누르세요.")
    print(f"저장 위치: {args.out}")

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context(viewport={"width": 1280, "height": 900})
        page = context.new_page()
        page.goto("https://www.facebook.com/login", wait_until="domcontentloaded")
        try:
            input("\n로그인 완료 후 Enter… ")
        except EOFError:
            deadline = time.time() + max(30, args.timeout_sec)
            print("대화형 입력이 없어 c_user 쿠키를 기다립니다…")
            while time.time() < deadline:
                names = {c.get("name") for c in context.cookies()}
                if "c_user" in names and "xs" in names:
                    break
                time.sleep(2)
            else:
                print(
                    "제한 시간 안에 Facebook 로그인 쿠키를 못 찾았습니다.",
                    file=sys.stderr,
                )
                browser.close()
                return 1

        cookies = context.cookies()
        fb_cookies = [
            c
            for c in cookies
            if "facebook.com" in (c.get("domain") or "")
            or "fb.com" in (c.get("domain") or "")
        ]
        if not any(c.get("name") == "c_user" for c in fb_cookies):
            print(
                "Facebook 로그인 쿠키(c_user)가 없습니다. 로그인 후 다시 시도하세요.",
                file=sys.stderr,
            )
            browser.close()
            return 1

        _write_netscape(fb_cookies, args.out)
        browser.close()

    print(f"저장 완료: {args.out} ({len(fb_cookies)} cookies)")
    print("api/.env 에 다음을 넣고 API/worker 를 재시작하세요:")
    print(f"  YTDLP_COOKIES_FILE={args.out.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
