#!/usr/bin/env bash
# One-time: create a Cloudflare named tunnel for api.dubbyai.com → :8000
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

TUNNEL_NAME="${DUBBY_TUNNEL_NAME:-dubby-api}"
HOSTNAME="${DUBBY_API_HOSTNAME:-api.dubbyai.com}"
CF=""
CONFIG_DIR="$ROOT/infra/cloudflared"
CONFIG_FILE="$CONFIG_DIR/config.yml"

find_cloudflared() {
  if [[ -x /tmp/cloudflared.exe ]]; then CF=/tmp/cloudflared.exe; return; fi
  if [[ -n "${LOCALAPPDATA:-}" && -x "$LOCALAPPDATA/Temp/cloudflared.exe" ]]; then
    CF="$LOCALAPPDATA/Temp/cloudflared.exe"
    return
  fi
  if command -v cloudflared >/dev/null 2>&1; then CF="$(command -v cloudflared)"; return; fi
  echo "Downloading cloudflared…"
  curl -sL -o /tmp/cloudflared.exe \
    https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe
  CF=/tmp/cloudflared.exe
}

find_cloudflared
mkdir -p "$CONFIG_DIR"

echo "1) Browser login to Cloudflare (select the dubbyai.com account/zone)…"
"$CF" tunnel login

echo "2) Ensure tunnel '$TUNNEL_NAME' exists…"
if ! "$CF" tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
  "$CF" tunnel create "$TUNNEL_NAME"
fi

TUNNEL_ID="$("$CF" tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$1==n || $2==n {print $1; exit}')"
if [[ -z "$TUNNEL_ID" ]]; then
  # Fallback: parse JSON if available
  TUNNEL_ID="$("$CF" tunnel list --output json 2>/dev/null | python -c "import json,sys; data=json.load(sys.stdin); print(next((t['id'] for t in data if t.get('name')==sys.argv[1]),''))" "$TUNNEL_NAME" || true)"
fi
if [[ -z "$TUNNEL_ID" ]]; then
  echo "ERROR: could not resolve tunnel id for $TUNNEL_NAME"
  "$CF" tunnel list || true
  exit 1
fi
echo "TUNNEL_ID=$TUNNEL_ID"

echo "3) Route DNS $HOSTNAME → tunnel (idempotent)…"
"$CF" tunnel route dns -f "$TUNNEL_NAME" "$HOSTNAME" || \
  "$CF" tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" || true

CRED=""
if [[ -n "${USERPROFILE:-}" && -f "$USERPROFILE/.cloudflared/$TUNNEL_ID.json" ]]; then
  CRED="$USERPROFILE/.cloudflared/$TUNNEL_ID.json"
elif [[ -f "$HOME/.cloudflared/$TUNNEL_ID.json" ]]; then
  CRED="$HOME/.cloudflared/$TUNNEL_ID.json"
else
  echo "ERROR: credentials JSON not found for $TUNNEL_ID under ~/.cloudflared"
  exit 1
fi

# Normalize path for YAML on Windows (forward slashes)
CRED_YAML="$(printf '%s' "$CRED" | sed 's|\\|/|g')"

cat >"$CONFIG_FILE" <<EOF
# Generated by scripts/setup-named-tunnel.sh — do not commit.
tunnel: $TUNNEL_ID
credentials-file: $CRED_YAML

ingress:
  - hostname: $HOSTNAME
    service: http://127.0.0.1:8000
  - service: http_status:404
EOF

# Publish pointer for mobile clients that still read api-origin.json
NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
cat >"$ROOT/public/api-origin.json" <<EOF
{
  "api_origin": "https://$HOSTNAME",
  "updated_at": "$NOW"
}
EOF

echo
echo "Wrote $CONFIG_FILE"
echo "Wrote public/api-origin.json → https://$HOSTNAME"
echo
echo "Next:"
echo "  1) Start uvicorn on :8000"
echo "  2) bash scripts/run-named-tunnel.sh"
echo "  3) GitHub secret NEXT_PUBLIC_API_ORIGIN=https://$HOSTNAME"
echo "  4) api/.env CORS_ORIGINS must include https://dubbyai.com"
echo "  5) Commit/push public/api-origin.json if changed"
echo
echo "See docs/CUSTOM_DOMAIN.md"
